# Generated by Django 2.0.6 on 2019-06-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'ストック', 'verbose_name_plural': 'ストック'},
        ),
    ]
